### ISSUE TITLE
C# & Unity learn

### ISSUE THREAD

**Issue by fenglwei** [swordsman-2018/Swordsman.RogueLike#1]
JX需要学习并掌握unity3d引擎

**Comment by hoppergee** [comment]
## U3d Resources

* [史上最全Unity3D教程](https://www.bilibili.com/video/av28779788?from=search&seid=5026739576410494437)
* [U3D官方21个案例技巧教程，中文翻译注释，助你快速掌握展UV技巧](https://www.bilibili.com/video/av34865963?from=search&seid=3674352354286656142)
* [Award Winning Tutorials from Unity](https://unity3d.com/cn/learn/tutorials)
* [Github Untiy Topic](https://github.com/topics/unity)
* [Github Unity2d Topic](https://github.com/topics/unity2d)
  * [Unity Script Collection](https://github.com/michidk/Unity-Script-Collection)
  * [Unity Library](https://github.com/UnityCommunity/UnityLibrary)
* [Awesome-unity](https://github.com/RyanNielson/awesome-unity)
* [Learn Unity By Making Games](https://github.com/shohan4556/learn-unity-by-making-games)
* [Unity Design Pattern](https://github.com/QianMo/Unity-Design-Pattern)
* [pixelnest.io](https://pixelnest.io/tutorials/)

### Book

* [Untiy in Action: Multiplatform game development in C#](https://www.amazon.com/Unity-Action-Multiplatform-game-development/dp/1617294969/ref=sr_1_1?ie=UTF8&qid=1543045157&sr=8-1&keywords=unity3d)
* [Unity From Zero to Proficiency (Beginner)](https://www.amazon.com/Unity-Proficiency-Beginner-step-step/dp/1980277478/ref=sr_1_8?ie=UTF8&qid=1543045157&sr=8-8&keywords=unity3d)

### Course

* [Complete C# Unity Developer 2D: Learn to Code Making Games](https://www.udemy.com/unitycourse/)
```
magnet:?xt=urn:btih:B6D4A20C108E46F96EA3AEB21D8BA9B98D2F61EC&dn=%5BUDEMY%5D+COMPLETE+C%23+UNITY+DEVELOPER+2D+%26ndash%3B+LEARN+TO+CODE+MAKING+GAMES+%5BFTU%5D&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fbigfoot1942.sektori.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fbt.xxx-tracker.com%3A2710%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=http%3A%2F%2Ft.nyaatracker.com%3A80%2Fannounce&tr=udp%3A%2F%2Fretracker.lanta-net.ru%3A2710%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.port443.xyz%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.vanitycore.co%3A6969%2Fannounce&tr=http%3A%2F%2Ftorrent.nwps.ws%3A80%2Fannounce&tr=udp%3A%2F%2Fipv6.open-internet.nl%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce
```

## C# Resources

* [这这大概是最好的C#入门教程了吧 - bilibili](https://www.bilibili.com/video/av2357992?share_medium=android&share_source=copy_link&bbid=5E6F372C-E061-43BD-AEC6-A74AD7097F0B18486infoc&ts=1542864798956)
* [Awesome Jet Light](https://amine-smahi.github.io/AwesomeJetLight/)
* [C# Official Discuss Repo](https://github.com/dotnet/csharplang)
* [Dotnet c# training tutorials](https://github.com/dotnet/training-tutorials/blob/master/content/csharp/getting-started/README.md)
* [C Sharp Algorithms](https://github.com/aalhour/C-Sharp-Algorithms)

### Person

[Anders Hejlsberg](https://github.com/ahejlsberg) - C# original designer and leader

### Book

* [C# in Depth](https://www.manning.com/books/c-sharp-in-depth-third-edition)
* The C# Player's Guide
* Illustrated C# 2012
* Illustrated C# 7
* Head First C#

### TDD in Unity

* [Tutorial Test Driven Developmen in Unity](https://forum.unity.com/threads/tutorial-test-driven-development-in-unity-updated.479222/)

### Others
* [Github for Unity](https://unity.github.com/)

**Comment by fenglwei** [comment]
- [【极客学院】Unity3D入门教学 + 附c#编程基础](https://www.bilibili.com/video/av10281109/?p=15)
- [【Unity 2D】基础讲解](https://www.bilibili.com/video/av24298754/?p=2)

**Comment by hoppergee** [comment]
`.gitignore` for unity project

```

# Created by https://www.gitignore.io/api/unity
# Edit at https://www.gitignore.io/?templates=unity

### Unity ###
[Ll]ibrary/
[Tt]emp/
[Oo]bj/
[Bb]uild/
[Bb]uilds/
Assets/AssetStoreTools*

# Visual Studio cache directory
.vs/

# Autogenerated VS/MD/Consulo solution and project files
ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.opendb
*.VC.db

# Unity3D generated meta files
*.pidb.meta
*.pdb.meta

# Unity3D Generated File On Crash Reports
sysinfo.txt

# Builds
*.apk
*.unitypackage

# Crashlytics generated file
Assets/StreamingAssets/crashlytics-build.properties


# End of https://www.gitignore.io/api/unity
```
