### ISSUE TITLE
给成员科普github的基本用法

### ISSUE THREAD

**Issue by fenglwei** [swordsman-2018/Swordsman.RogueLike#3]
JX靠你了

**Comment by hoppergee** [comment]
## 上手Git:

1. [Learn Git Branch](https://learngitbranching.js.org/)⭐⭐
2. [A Visual Git Reference](https://marklodato.github.io/visual-git-guide/index-en.html)

## 上手Github:

* [GitHub Work Flow](https://guides.github.com/introduction/flow/)
* [如何使用GitHub Issues](https://guides.github.com/features/issues/)

## 上手Markdown:

* [Markdown 用法](https://guides.github.com/features/mastering-markdown/)
