### ISSUE TITLE
玩法设计

### ISSUE THREAD

**Issue by fenglwei** [swordsman-2018/Swordsman.RogueLike#4]
游戏的设计、策划和数值麻烦在这里讨论

**Comment by LovelyNane** [comment]
总方针：招式命中-->攒能量（层数）——>施放功法
功法分为三种思路：1、功法自身分等级，1级，2级，……，顶级的是最强的，后期搭配就肯定会选用顶级，好处是玩家有成就感，每升一级都有不一样的体验，朝顶级努力，缺点是缺乏多元化。
                                 2、功法威力随人物属性增加，伤害、防御属性由内功决定，功法随着内功增加而增加威力，设置功法的自身属性（金木水火土），有相互克制或者相互增强的关系。
                                 3、在第2种的基础上，将功法发挥分层次，可分为3-5个层次，每拾取到一个功法的书籍残页，可以获得一个层次，每升级一个层次，施放功法的所需招式减少，功法威力增加。
       第2种和第3种的多元化较强，更多的是让玩家来决定怎样搭配属于自己喜欢的武功，缺点在于一个功法的威力发挥的数值和设置比较难。

**Comment by fenglwei** [comment]
**两种攒气方案：**
 **1.  abc就是横竖撇**
比如基础功法就是abc
高级招式可升级，捡一次升一级，比如a到aaa，就是一二三，b到bbb就是竖到川，c到cccc，就是点到两点水、三点水、四点底。有些更高级的功夫的招式假设这一招就是回字4a4b，也就是打一招就可以蓄出4a4b，可以打中对面无格挡时获得数量翻倍。总之，攒输入后期非常好获得，多笔画的字打两招也就凑够笔画。比如八卦掌的卦字，4a3b1a，8画基本是极限了，不考虑顺序的情况下，一个回加1个点就凑齐了。
这样的话找50个左右的武功也就是提炼50个字，最长的字也就是10画吧，高级招式甚至2下就蓄力完成。
**2. 像wow一样设定指示物**

**Comment by fenglwei** [comment]
内功设定：
随着等级增加增加，可增加各种数值，abc可储存的上限增加。
外功设定：
随着等级增加增加，可增加移动速度，招式携带量，招式可升级上限。

**Comment by fenglwei** [comment]
思考了一个晚上，在核心玩法上开始纠结，是因为2.5D视角回合制在游戏美术上的巨大工作量，导致有可能我们这个游戏未来开发上的搁浅，于是我把2种未来的游戏模式都列出来，让大家来讨论一下：

- 首先还是先阐述一下我要做什么样的武侠，我认为的中国武侠主要表现形式是侠义与武功的，侠义大，适合讲故事，看电影，我们的独立游戏不适合表现；那就要表现武功，中国武学，招式千变万化，却总有博弈克制，**我认为的武侠在游戏上就应该表现武功就要变现招式的搭配和博弈。**
**A.3D**
首先放弃3D，独立游戏如果做3D，核心玩法难创新，画面违和，实力资金都不够。
**B. 2.5D**
2.5D版本适合，即时战斗当然也可以，但是设计难度、美术工作都几何上升，而且国产太多的武侠，珠玉在前，即时就很难表现搭配和克制，爽就完事了。做成回合制，更能反映招式搭配和博弈，也更符合2.5D的。
那么如果做成回合制，就是最早设计的选择移动和攻击范围，在猜测对方位置和招式中做出选择，也可以增加如汉字的表现方式来呈现搭配、克制。
_优点：_
- 画面上更符合玩家对于武侠的审美；
- 程序上相对简单；
- 更容易表现轻功、武功搭配、招式博弈，也就更适合roguelike。
_缺点：_
- 游戏模式老旧，不一定能被大众所接受，有可能不好玩；
- 美术工作量极大，哪怕用3D建模转2D，招式的设计难度也非常高。
**C. 俯视2D**
俯视2D的版本，如果做成回合制，就非常难表现，俯视的版本多是即时制的，所以以下按照即时制来考虑，但如此游戏机制就需要变化，甚至roguelike也得改。要反映中国武侠，就需要区别于巫师3、荣耀战魂、骑马砍杀这种西方色彩，那么招式的投影还是需要的。
_优点：_
1. 美术的工作量大大减少，并且可以设计更为丰富的动作，画面360°均可转动；
2. 即时制更适合信息量较少的2D俯视视角；
3. 即时制更容易被现在的大众玩家接受。
_缺点：_
- Act的打击感，要人物动作音效特效打击反馈这些东西配合才能很好体现，较难配合；
- 俯视画面的信息较少，就需要更多的敌人或者更华丽的招式，更多的敌人与武侠比较违和；
- 招式的搭配更加像套皮魔兽世界；
- 即时制的玩家更注重游戏完整性，对游戏玩法要求更高。
_即时制的游戏玩法需要重新设计，因为即时制的输入有限，否则过于复杂，目前我想到的玩法：_
  1. 左右键攻击，数字键释放技能，有点类似魔兽世界了。。。。
  2. 123选择招式博弈，左键攻击，右键大招。
即时制的游戏模式需要大家再思考。
